/* autogenerated by Processing revision 1293 on 2025-10-30 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import controlP5.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.Comparator;
import javax.swing.JOptionPane;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Proyecto2 extends PApplet {









// ############################################### //
// ################## MetadataS ################## //
// ############################################### //

boolean pause = true;   //Pause the simulation
boolean start = true;   //Main menu of the simulation
boolean finish = false; //Finish for the simulation
int timer = -1;         //Timer for one advance frames
float offsetY = 0;      //Scroll
int scrollMaxCount;     //Scroll pages amount

// ################### <OTHER> ################### //

PFont hideFont;
PFont defaultFont;
PFont menuFontBig;
PFont menuFont;
PFont menuFontSmall;

// ############################################### //
// ################## ControlP5 ################## //
// ############################################### //

ControlP5 cp5;
Button pausa;
Button inicio;
Button menu;
Button crear;
Button cargar;
Button jump;
Slider frameRateSlider;
float framerate = 60;
float limitFrames = 600;

RadioButton menuProcesos;
int procesos = 10;
RadioButton menuOperaciones;
int operaciones = 500;
RadioButton menuAlgoritmo;
int algoritmo = 0;
Textfield menuSemilla;
int semilla = 0;

// ############################################### //
// ################ Regex Patterns ############### //
// ############################################### //

String patronNew    = "new\\(.*";
String patronDelete = "delete\\(.*";
String patronUse    = "use\\(.*";
String patronKill   = "kill\\(.*";

// ############################################### //
// ################## Simulation ################# //
// ############################################### //

MUM mum;

ALG OPT;
ALG ALG;
ALG FIFO;
ALG SC;
ALG MRU;
ALG RND;

int mmuMax;

String instrucciones;
String[] listaInstrucciones;
int indice = -1;

// ############################################### //
// ################### < SETUP > ################# //
// ############################################### //

public void setup(){
  /* size commented out by preprocessor */;
  //size(1200, 600);
  
  //Color mode
  colorMode(HSB, 360, 100, 100);
  
  hideFont = createFont("Arial", 1);
  defaultFont = createFont("SansSerif", 10);
  menuFontBig = createFont("8bitOperatorPlus8-Regular.ttf", 50);
  menuFontSmall = createFont("8bitOperatorPlus8-Regular.ttf", 15);
  menuFont = createFont("8bitOperatorPlus8-Regular.ttf", 20);
  
  cp5 = new ControlP5(this);
  
  //Slider framerate 
  frameRateSlider = cp5.addSlider("framerate")
          .setPosition(width/12 + 100, height/16)
          .setSize(width/3, 20)
          .setRange(5, limitFrames)
          .setValue(framerate)
          .setCaptionLabel("");
  frameRateSlider.hide();
          //.setFont(sliderFont)
          
  jump = cp5.addButton("jump")
     .setLabel(">")
     .setPosition(width/12 + 70, height/16)
     .setSize(20, 20);
  jump.hide();
  
  pausa = cp5.addButton("pausa")
     .setLabel("Pausar")
     .setPosition(width/12, height/16)
     .setSize(60, 20);
  pausa.hide();
  
  menu = cp5.addButton("menu")
     .setLabel("Menu")
     .setPosition(5*width/12 + 110, height/16)
     .setSize(60, 20);
  menu.hide();
  
  crear = cp5.addButton("crear")
     .setLabel("Crear")
     .setPosition(width/2 + 150, height/2)
     .setSize(80, 25)
     .setFont(menuFont);
     
  cargar = cp5.addButton("cargar")
     .setLabel("Cargar")
     .setPosition(width/2 + 150, height/2 + 30)
     .setSize(80, 25)
     .setFont(menuFont);
  
  inicio = cp5.addButton("inicio")
     .setLabel("Inicio")
     .setPosition(width/2, 3*height/4)
     .setSize(120, 40)
     .setFont(menuFont);
     
  menuProcesos = cp5.addRadioButton("mprocesos")
    .setPosition(width/2 - width/5, height/4)
    .setSize(25, 25)
    .setItemsPerRow(1)
    .setSpacingRow(6)
    .addItem("10", 10)
    .addItem("50", 50)
    .addItem("100", 100)
    .activate(procesos)
    .setFont(menuFont);
    
  menuOperaciones = cp5.addRadioButton("moperaciones")
    .setPosition(width/2, height/4)
    .setSize(25, 25)
    .setItemsPerRow(1)
    .setSpacingRow(6)
    .addItem("500", 500)
    .addItem("1000", 1000)
    .addItem("5000", 5000)
    .activate(operaciones)
    .setFont(menuFont);
    
  menuAlgoritmo = cp5.addRadioButton("malgoritmo")
    .setPosition(width/2 + width/5, height/4)
    .setSize(25, 25)
    .setItemsPerRow(1)
    .setSpacingRow(6)
    .addItem("FIFO", 0)
    .addItem("SC", 1)
    .addItem("MRU", 2)
    .addItem("RND", 3)
    .activate(algoritmo)
    .setFont(menuFont);
    
  menuSemilla = cp5.addTextfield("inputSemilla")
    .setPosition(width/2, height/2)
    .setSize(120, 25)
    .setAutoClear(false)
    .setInputFilter(ControlP5.INTEGER)
    .setText(str(PApplet.parseInt(semilla)))
    .setLabel("Semilla")
    .setFont(menuFont);
    
    
    
  for (Toggle t : menuProcesos.getItems()) {
    t.getCaptionLabel().setFont(menuFont);
    t.getCaptionLabel().setColor(color(0));
  }
  for (Toggle t : menuOperaciones.getItems()) {
    t.getCaptionLabel().setFont(menuFont);
    t.getCaptionLabel().setColor(color(0));
  }
  for (Toggle t : menuAlgoritmo.getItems()) {
    t.getCaptionLabel().setFont(menuFont);
    t.getCaptionLabel().setColor(color(0));
  }
  menuSemilla.getCaptionLabel().setColor(color(0));
  
  mmuMax = 6;
  mum = new MUM();
  mum.setRandom(semilla);
  mum.setProcesses(procesos);
  instrucciones = mum.randomInstructions(operaciones);
  listaInstrucciones = instrucciones.split("\\R");
  
  OPT = new OPT();
  listaTraducida = new ArrayList<Integer>();

  scrollMaxCount = ((3*height/8)/15)-2;
}

public void draw(){
  
  if (start){ //Menu Principal
  
    background(0xFFCECECE);
    fill(0);
    
    textFont(menuFontSmall);
    fill(0);
    text("Cantidad Procesos",     width/2 - width/5, height/4 - 5);
    text("Cantidad Intrucciones", width/2          , height/4 - 5);
    text("Algoritmo",             width/2 + width/5, height/4 - 5);
    textFont(defaultFont);

    
  } else { //Simulacion Principal
    
    background(200);
    
    translate(0, offsetY);
    frameRate(framerate);
    
    
    OPT.display();
    ALG.display();
    
    
    if (!pause && !finish){
      
      indice++;
      String instruccion;
      if (indice >= listaInstrucciones.length){
        instruccion = "NOP No Operation";
        finish = true;
      } else {
        instruccion = listaInstrucciones[indice];
      }
      
      
      
      OPT.update(instruccion);
      ALG.update(instruccion);
      
    } else if (finish) {
      
      textFont(menuFont);
      text("Simulación Finalizada :D", 5*width/12 + 180, height/16 + 15);
      textFont(defaultFont);
      
    }
    
    
    
    drawMemoryFromPages(OPT);
    drawMemoryFromPages(ALG);
    
    drawPages(OPT.pages, 0);
    drawPages(ALG.pages, 1);
  }
  
  
  if (timer == 0){
    pause = true;
    timer--;
  } else if (timer > 0) {
    pause = false;
    timer--;
  }
}








public void menu(){ //Boton
  start = true;
  
  menuProcesos.show();
  menuOperaciones.show();
  menuAlgoritmo.show();
  menuSemilla.show();
  inicio.show();
  cargar.show();
  crear.show();
   
  frameRateSlider.hide();
  pausa.hide();
  jump.hide();
  menu.hide();
}



public void startSimulation(){
  textFont(defaultFont);
  
  pause = true;
  finish = false;
  pausa.setLabel("Iniciar");
   
  menuProcesos.hide();
  menuOperaciones.hide();
  menuAlgoritmo.hide();
  menuSemilla.hide();
  inicio.hide();
  cargar.hide();
  crear.hide();
   
  frameRateSlider.show();
  pausa.show();
  jump.show();
  menu.show();
  
  indice = -1;
  
  
  switch (algoritmo){
    case 0:
      ALG = new FIFO();
      break;
      
    case 1:
      ALG = new SC();
      break;
      
    case 2:
      ALG = new MRU();
      break;
      
    case 3:
      ALG = new RND();
      break;
  }
  OPT = new OPT();
  
  listaTraducida.clear();
  traducir(listaInstrucciones);
  OPT.processes = procesos;
  OPT.time = 0;
  
  ALG.processes = procesos;
  ALG.time = 0;
}


enum Algorythm {
  OPT, FIFO, SC, MRU, RND
}



abstract class ALG{


    List<Page> pages;
    Random rand;

    int lastPageID;
    int lastPtr;
    int processes;
    int time;

    int ramKB;
    float ramPercentage;
    int virtualRamKB;
    float virtualRamPercentage;

    int loadedPages;
    int unloadedPages;

    int thrashingTime;
    float thrashingPercentage;
    int fragmentation; // le cambie el nombre

    Algorythm algorythm;


    ALG(){

        this.pages = new ArrayList<Page>();
        this.rand = new Random();

        this.lastPageID = 0;
        this.lastPtr = 0;
        this.processes = 0;
        this.time = 0;

        this.ramKB = 0;
        this.virtualRamKB = 0;

        this.loadedPages = 0;
        this.unloadedPages = 0;

        this.thrashingTime = 0;
    }


    public void setProcesses(int processes) {
        this.processes += processes;
    }

    public void increaseTime(int seconds) {
        this.time += seconds;
    }

    public void setRamKB(int ramKB) {
        this.ramKB += ramKB;
    }

    public void setRamPercentage() {
        this.ramPercentage =  ((float) this.ramKB) / 400;
    }

    public void setVirtualRamKB(int virtualRamKB) {
        this.virtualRamKB += virtualRamKB;
    }

    public void setVirtualRamPercentage() {
        this.virtualRamPercentage = ((float) this.virtualRamKB) / 400;
    }

    public void setLoadedPages(int loadedPages) {
        this.loadedPages += loadedPages;
    }

    public void setUnloadedPages(int unloadedPages) {
        this.unloadedPages += unloadedPages;
    }

    public void increaseThrashingTime(int seconds) {
        this.thrashingTime += seconds;
    }

    public void setThrashingPercentage() {
        this.thrashingPercentage = ((float) this.thrashingTime) / ((float) this.time);
    }

    public void setFragmentation(int fragmentation) {
        this.fragmentation = fragmentation;
    }

    public abstract void callNew(int pid, int size);
    public abstract void callUse(int ptr);
    public abstract void callDelete(int ptr);
    public abstract void callKill(int pid);





    public void update(String instruccion){
        int n;
        int openID  = instruccion.indexOf('(');
        int closeID = instruccion.lastIndexOf(')');

        if (instruccion.matches(patronUse)){
            n = Integer.parseInt(instruccion.substring(openID + 1, closeID).trim());
            callUse(n);

        } else if (instruccion.matches(patronNew)){
            String[] temp = instruccion.substring(openID + 1, closeID).split("\\s*,\\s*");
            n = Integer.parseInt(temp[0]);
            int size = Integer.parseInt(temp[1]);
            callNew(n, size);

        } else if (instruccion.matches(patronDelete)){
            n = Integer.parseInt(instruccion.substring(openID + 1, closeID).trim());
            callDelete(n);

        } else if (instruccion.matches(patronKill)){
            n = Integer.parseInt(instruccion.substring(openID + 1, closeID).trim());
            callKill(n);

        } else {
            //println("Angy ¯\\_(=/)_/¯");
        }
    }

    public void display(){

        int ancho = width/12;
        int altura = 15;
        String name;
        
        switch (algorythm) {
          case FIFO:
            name = "FIFO";
            break;
          case SC:
            name = "Second Chance";
            break;
          case MRU:
            name = "MRU";
            break;
          case RND:
            name = "Random";
            break;
          default:
            name = "OPT";
            break;
        }

        int y = height/4 + 50;
        int x = algorythm == Algorythm.OPT ? 0 : width/2;

        textFont(menuFontBig);
        
        fill(179, 100, 100);
        text(name, x+ancho , y + altura - 25);
        //fill(240, 100, 100);
        //text(name, x+ancho +4, y + altura - 40);
        fill(0);
        text(name, x+ancho +4, y + altura - 25);

        textFont(defaultFont);

        fill(360);
        rect(x+ancho, y, ancho*2, altura);
        fill(0);
        text("Processes", x+ancho +1, y + altura - 1);

        fill(360);
        rect(x+3*ancho, y, ancho*2, altura);
        fill(0);
        text("Simulation Time", x+3*ancho +1, y + altura - 1);

        //\\ y //\\
        y += altura;

        fill(360);
        rect(x+ancho, y, ancho*2, altura*2);
        fill(0);
        text(processes, x+ancho +10, y + altura*1.5f - 1);

        fill(360);
        rect(x+3*ancho, y, ancho*2, altura*2);
        fill(0);
        text(time + "s", x+3*ancho +10, y + altura*1.5f - 1);

        //\\ y //\\
        y += altura;
        y += altura;
        y += altura;

        fill(360);
        rect(x+ancho, y, ancho, altura);
        fill(0);
        text("RAM KB", x+ancho +1, y + altura - 1);

        fill(360);
        rect(x+2*ancho, y, ancho, altura);
        fill(0);
        text("RAM %", x+2*ancho +1, y + altura - 1);

        fill(360);
        rect(x+3*ancho, y, ancho, altura);
        fill(0);
        text("V-RAM KB", x+3*ancho +1, y + altura - 1);

        fill(360);
        rect(x+4*ancho, y, ancho, altura);
        fill(0);
        text("V-RAM %", x+4*ancho +1, y + altura - 1);

        //\\ y //\\
        y += altura;

        fill(360);
        rect(x+ancho, y, ancho, altura);
        fill(0);
        text(ramKB, x+ancho +1, y + altura - 1);

        fill(360);
        rect(x+2*ancho, y, ancho, altura);
        fill(0);
        text(nf(ramPercentage * 100, 2, 2) + "%", x+2*ancho +1, y + altura - 1);

        fill(360);
        rect(x+3*ancho, y, ancho, altura);
        fill(0);
        text(virtualRamKB, x+3*ancho +1, y + altura - 1);

        fill(360);
        rect(x+4*ancho, y, ancho, altura);
        fill(0);
        text(nf(virtualRamPercentage * 100, 2, 2) + "%", x+4*ancho +1, y + altura - 1);

        //\\ y //\\
        y += altura;
        y += altura;

        fill(360);
        rect(x+ancho, y, ancho*2, altura);
        fill(0);
        text("PAGES", x+ancho +1, y + altura - 1);

        if (thrashingTime > time*0.5f){
            fill(0, 68, 99);
        } else {
            fill(360);
        }
        rect(x+3*ancho, y, ancho, altura);
        fill(0);
        text("Thrashing", x+3*ancho +1, y + altura - 1);

        fill(360);
        rect(x+4*ancho, y, ancho, altura);
        fill(0);
        text("Fragmentacion", x+4*ancho +1, y + altura - 1);

        //\\ y //\\
        y += altura;

        fill(360);
        rect(x+ancho, y, ancho, altura);
        fill(0);
        text("LOADED", x+ancho +1, y + altura - 1);

        fill(360);
        rect(x+2*ancho, y, ancho, altura);
        fill(0);
        text("UNLOADED", x+2*ancho +1, y + altura - 1);

        if (thrashingTime > time*0.5f){
            fill(0, 68, 99);
        } else {
            fill(360);
        }
        rect(x+3*ancho, y, ancho/2, altura*2);
        fill(0);
        text(thrashingTime + "s", x+3*ancho +1, y + altura*1.5f - 1);

        if (thrashingTime > time*0.5f){
            fill(0, 68, 99);
        } else {
            fill(360);
        }
        rect(3.5f*ancho+x, y, ancho/2, altura*2);
        fill(0);
        text(nf(thrashingPercentage * 100, 2, 2) + "%", 3.5f*ancho+x +1, y + altura*1.5f - 1);

        fill(360);
        rect(4*ancho+x, y, ancho, altura*2);
        fill(0);
        text(fragmentation + " KB", 4*ancho+x +1, y + altura*1.5f - 1);

        //\\ y //\\
        y += altura;

        fill(360);
        rect(x+ancho, y, ancho, altura);
        fill(0);
        text(loadedPages, x+ancho +1, y + altura - 1);

        fill(360);
        rect(x+2*ancho, y, ancho, altura);
        fill(0);
        text(unloadedPages, x+2*ancho +1, y + altura - 1);
    }
}


public void mouseWheel(MouseEvent event){
  int mmuMax = max(OPT.pages.size(), ALG.pages.size());
  int x = max(mmuMax - scrollMaxCount, 0);
  offsetY -= event.getCount() * 25;
  offsetY = constrain(offsetY, -x * 15, 0);
}











public void controlEvent(ControlEvent e) {
  if (e.isFrom(menuProcesos)) {
    procesos = PApplet.parseInt(e.getValue());
  } else if (e.isFrom(menuOperaciones)) {
    operaciones = PApplet.parseInt(e.getValue());
  } else if (e.isFrom(menuAlgoritmo)) {
    algoritmo = PApplet.parseInt(e.getValue());
  }
}








public void pausa(){
  if(!start){
    pause = !pause;
    
    if (pause){
      pausa.setLabel("Reanudar");
    } else {
      pausa.setLabel("Pausar");
    }
  }
}

public void jump(){
  timer = 1;
}

public void inicio(){ //Boton
  start = false;
  startSimulation();
}

public void crear(){ //Boton
  
  mum.setRandom(semilla);
  mum.setProcesses(procesos);

  instrucciones = mum.randomInstructions(operaciones);
  listaInstrucciones = instrucciones.split("\\R");
  
  
  
  int respuesta = JOptionPane.showConfirmDialog(
    null,
    "¿Desea guardar las instrucciones generadas?",
    "Guardar Archivo",
    JOptionPane.YES_NO_OPTION
  );
  
  if (respuesta == JOptionPane.YES_OPTION) {
    selectOutput("Elige donde guardar el archivo:", "archivoGuardado");
  }
}

public void cargar(){ //Boton
  
  selectInput("Selecciona un archivo a cargar:", "archivoSeleccionado");
  
}









public void inputSemilla(String txt){
  if (txt == null || txt.length() == 0) return;
  
  try {
    float v = PApplet.parseFloat(txt);
    menuSemilla.setText(str(PApplet.parseInt(v)));
    semilla = (int) v;
  } catch (Exception ex) {
    // error/invalido (?)
  }
}


public void pruebaMUM(){
  MUM mum = new MUM();

  mum.setRandom(811);
  mum.setProcesses(100);

  System.out.println(mum.randomInstructions(5));
}



private final class Pointer {
    private final int pid;
    private final int ptr;

    public Pointer(int pid, int ptr) {
        this.pid = pid;
        this.ptr = ptr;
    }

    public int getPid() {
        return pid;
    }

    public int getPtr() {
        return ptr;
    }
}

public class MUM {
    private int nextPtr;
    private List<Integer> processes;
    private List<Pointer> pointers;
    private Random rand = new Random();
    
    public MUM() {
      this.nextPtr = 0;
      this.processes = new ArrayList<>();
      this.pointers = new ArrayList<>();
      this.processes.clear();
      this.pointers.clear();
    }

    public void setRandom(long seed) {
        this.rand = new Random(seed);
    }

    public void setProcesses(int quantity) {
        processes.clear();
        for (int i = 0; i < quantity; i++) {
            processes.add(i);
        }
    }

    public boolean isAlive(int pid) {
        return processes.contains(pid);
    }

    public boolean newPtr(int pid) {
        if (!isAlive(pid)) return false;
        pointers.add(new Pointer(pid, nextPtr++));
        return true;
    }

    public void deletePtr(int ptr) {
        for (int i = 0; i < pointers.size(); i++) {
            if (pointers.get(i).getPtr() == ptr) {
                pointers.remove(i);
                break;
            }
        }
    }

    public void killPid(int pid) {
        pointers.removeIf(p -> p.getPid() == pid);
        processes.remove(Integer.valueOf(pid));
    }

    private String randomNew() {
        int pid = rand.nextInt(processes.size());
        pid = processes.get(pid);
        int x = rand.nextInt(25);
        double y = rand.nextDouble();
        int size = rand.nextInt((int) ((x*4000) + (y*4000)));
        if (newPtr(pid)) {
            return "new(" + pid + ", " + size +")\n";
        }
        return "";
    }

    private String randomUse() {
        int ptr = rand.nextInt(pointers.size());
        ptr = pointers.get(ptr).getPtr();
        return "use(" + ptr + ")\n";
    }

    private String randomDelete() {
        int ptr = rand.nextInt(pointers.size());
        ptr = pointers.get(ptr).getPtr();
        deletePtr(ptr);
        return "delete(" + ptr + ")\n";
    }

    private String randomKill() {
        int pid = rand.nextInt(processes.size());
        pid = processes.get(pid);
        killPid(pid);
        return "kill(" + pid + ")\n";
    }

    private String randomInstruction() {
        String command;
        double chance = rand.nextDouble();
        if (pointers.isEmpty()) {
            if (chance < (double) 63/64 || processes.size() == 1) {
                command = randomNew();
            }
            else {
                command = randomKill();
            }
        }
        else {
            if (processes.size() == 1) {
                if (chance < (double) 1/3) {
                    command = randomNew();
                } else if (chance < (double) 2/3) {
                    command = randomUse();
                } else {
                    command = randomDelete();
                }
            } else {
                    if (chance < (double) 21/64) {
                        command = randomNew();
                    } else if (chance < (double) 21/32) {
                        command = randomUse();
                    } else if (chance < (double) 63/64) {
                        command = randomDelete();
                    } else {
                        command = randomKill();
                    }
            }
        }
        return command;
    }

    public String randomInstructions(int quantity) {
        this.pointers.clear();
        this.nextPtr = 0;
        StringBuilder command = new StringBuilder();
        for (int i = 0; i < quantity; i++) {
            command.append(randomInstruction());
        }
        return command.toString();
    }
}
public void archivoSeleccionado(File seleccion) {
  
  
  if (seleccion == null) {
    println("No se seleccionó ningún archivo.");
  } else {
    listaInstrucciones = loadStrings(seleccion);
    for(int i = 0; i < listaInstrucciones.length; i++){
       println(listaInstrucciones[i]);
    }
    println("Archivo seleccionado: " + seleccion.getAbsolutePath());
  }
}

public void archivoGuardado(File seleccion) {//Este metodo guarda el archivo a partir de una ejecucion
  if (seleccion == null) {
    println("No se eligió destino.");
  } else {
    // ruta completa del archivo elegido por el usuario
    String ruta = seleccion.getAbsolutePath();

    // si el archivo no tiene extensión, se agrega .txt automáticamente
    if (!ruta.endsWith(".txt")) {
      ruta += ".txt";
    }

    saveStrings(ruta, instrucciones.split("\n"));

    println("Archivo guardado en: " + ruta);
  }
}

List<Integer> listaTraducida;


public void traducir(String[] listaInstrucciones){
      
  OPT.lastPtr = 0;
  listaTraducida.clear();
  
  String instruccion;
  for (int i = 0; i < listaInstrucciones.length; ++i){
    
    instruccion = listaInstrucciones[i];
    
    int n;
    int openID  = instruccion.indexOf('(');
    int closeID = instruccion.lastIndexOf(')');

    if (instruccion.matches(patronUse)){
      n = Integer.parseInt(instruccion.substring(openID + 1, closeID).trim());
      listaTraducida.add(n);

    } else if (instruccion.matches(patronNew)){
      listaTraducida.add(OPT.lastPtr);
      OPT.lastPtr++;

    } else {
      listaTraducida.add(-1);
    }
  }
  
  OPT.lastPtr = 0;
}












private class OPT extends Pager{
  

  
    OPT(){
      this.algorythm = Algorythm.OPT;
    }
    
    


    
    
    
    @Override
    protected int whoToUnload() {
      int ptr = -1;
      // indice (instriccion actual)
      int maxPos = -1;

      for (int i = indice+1; i < listaTraducida.size(); ++i){
        int currentPagePtr = listaTraducida.get(i);

        if (currentPagePtr != -1 && super.isLoaded(currentPagePtr)){
          //El puntero no es invalido
          //La primera pagina del puntero esta cargada
          
          int currentPos = nextPos(indice+1, listaTraducida.get(i));
          
          if (currentPos > maxPos){
            maxPos = currentPos;
            ptr = listaTraducida.get(i);
          }
        }
      }
      
      if (ptr == -1){ //Si el puntero es invalido elimina a cualquiera
        for (Page page : pages){
          if (super.isLoaded(page.laddr)){
            return page.laddr;
          }
        }
      }
        
      return ptr;
    }
    
    private int nextPos(int start, int page){
      for (int i = start; i < listaTraducida.size(); ++i){
        if (page == listaTraducida.get(i)){
          return i;
        }
      }
      
      return -1;
    }

}
public abstract class Pager extends ALG {


    public Pager() {}

    protected void incrementTimes(int seconds, boolean thrashing) {
        for  (Page p : pages) {
            if (p.loaded) {
                p.incrementTime(seconds);
            }
        }

        this.increaseTime(seconds);

        if (thrashing) {
            this.increaseThrashingTime(seconds);
        }
    }

    protected void loadPages(List<Page> pages, boolean isNew, boolean loaded) {
        for (Page page : pages) {
            page.loaded = true;
            page.daddr = 0;
            page.maddr = 0;
            if (isNew && !loaded) {
                this.pages.add(page);
            }
        }

        setMADDRs();

        if (isNew || !loaded) {
            this.setRamKB(pages.size() * 4);
            this.setLoadedPages(pages.size());
        }

        if (!isNew && !loaded) {
            setVirtualRamKB(pages.size() * 4 * -1);
            setUnloadedPages(pages.size() * -1);
        }
    }

    protected void unloadPages(int ptr) {
        List<Page> toUnload = getPagesbyPtr(ptr);
        for  (Page p : toUnload) {
            p.loaded = false;
            p.daddr = 0;
            p.loadedtime = 0;
            p.maddr = 0;
        }

        setDADDRs();

        this.setRamKB(toUnload.size() * 4 * -1);
        this.setLoadedPages(toUnload.size() * -1);

        this.setVirtualRamKB(toUnload.size() * 4);
        this.setUnloadedPages(toUnload.size());
    }

    public void callNew(int pid, int size) {
        int pagesNeeded = size / 4000;
        int lastPageSpace = size % 4000;
        List<Page> newPages = new ArrayList<>();

        // Crear paginas
        for (int i = 0; i < pagesNeeded; ++i) {
            newPages.add(new Page(++this.lastPageID, pid, this.lastPtr, 4000));
        }
        if (lastPageSpace != 0)
            newPages.add(new Page(++this.lastPageID, pid, this.lastPtr++, lastPageSpace));
        else
            ++this.lastPtr;

        // Liberar espacio necesario
        int spaceNeeded = sizeNeeded(newPages);
        int freeMemory = getFreeMemory();
        int hits = Math.min(newPages.size(), freeMemory / 4000);
        int misses = newPages.size() - hits;
        while (freeMemory < spaceNeeded) {
            this.unloadPages(whoToUnload());
            freeMemory = getFreeMemory();
        }

        // Cargar Informacion a las paginas y agregarlas
        loadPages(newPages, true, false);
        this.incrementTimes(hits, false);
        this.incrementTimes(5 * misses, true);
        updateInfo();
    }

    public void callUse(int ptr) {
        // Obtener paginas con el puntero
        List<Page> usePages = getPagesbyPtr(ptr);

        // Liberar espacio necesario
        int hits, misses;
        boolean loaded;
        if (!isLoaded(ptr)) {
            int spaceNeeded = sizeNeeded(usePages);
            int freeMemory = getFreeMemory();
            hits = Math.min(usePages.size(), freeMemory / 4000);
            misses = usePages.size() - hits;
            while (freeMemory < spaceNeeded) {
                this.unloadPages(whoToUnload());
                freeMemory = getFreeMemory();
            }
            loaded = false;
        } else {
            hits = usePages.size();
            misses = 0;
            loaded = true;
        }

        // Cargar Informacion a las paginas llamadas
        loadPages(usePages, false, loaded);
        this.incrementTimes(hits, false);
        this.incrementTimes(5 * misses, true);
        updateInfo();
    }

    public void callDelete(int ptr) {
        List<Page> found = this.getPagesbyPtr(ptr);
        int hits = countLoaded(found);
        int misses = found.size() - hits;
        
        this.deletePagesStats(found);
        pages.removeIf(page -> page.laddr == ptr);
        
        this.incrementTimes(hits, false);
        this.incrementTimes(5 * misses, true);
        updateInfo();
    }

    public void callKill(int pid) {
        List<Page> found = this.getPagesbyPid(pid);
        int hits = countLoaded(found);
        int misses = found.size() - hits;
      
        this.deletePagesStats(found);
        this.processes--;
        pages.removeIf(page -> page.pid == pid);
        
        this.incrementTimes(hits, false);
        this.incrementTimes(5 * misses, true);
        updateInfo();
    }

    private boolean isLoaded(int ptr) {
        for  (Page p : pages) {
            if (p.laddr == ptr && p.loaded) {
                return true;
            }
        }
        return false;
    }
    
    private int countLoaded(List<Page> toCount) {
      int result = 0;
      for (Page p : toCount){
        if(p.loaded)
          result++;
      }
      return result;
    }


    private void deletePagesStats(List<Page> toDelete) {
        for  (Page p : toDelete) {
            if (p.loaded) {
                this.setRamKB(-4);
                this.setLoadedPages(-1);
            } else {
                this.setVirtualRamKB(-4);
                this.setUnloadedPages(-1);
            }
        }
    }

    protected List<Page> getPagesbyPtr(int ptr) {
        List<Page> result = new ArrayList<>();
        for  (Page page : pages) {
            if(page.laddr == ptr) {
                result.add(page);
            }
        }
        return result;
    }

    protected List<Page> getPagesbyPid(int pid) {
        List<Page> result = new ArrayList<>();
        for  (Page page : pages) {
            if(page.pid == pid) {
                result.add(page);
            }
        }
        return result;
    }

    private int getFreeMemory() {
        int freeMemory = 400000;
        for  (Page page : pages) {
            if (page.loaded) {
                freeMemory -= 4000;
            }
        }
        return freeMemory;
    }

    private int sizeNeeded(List<Page> p) {
        return 4000 *  p.size();
    }

    private void getFragmentation(){
        int fragmentation = 0;
        for (Page page : pages) {
            if (page.loaded) {
                fragmentation += 4000 - page.memoryUsed;
            }
        }
        fragmentation /= 4000;
        setFragmentation(fragmentation);
    }

    public void updateInfo() {
        setRamPercentage();
        setVirtualRamPercentage();
        setThrashingPercentage();
        getFragmentation();
    }

    private void setMADDRs() {
        int nextMADDRs = 0;
        for (Page page : pages) {
            if (page.loaded) {
                page.maddr = ++nextMADDRs;
            }
        }
    }


    private void setDADDRs() {
        int nextDADDRs = 0;
        for (Page page : pages) {
            if (!page.loaded) {
                page.daddr = ++nextDADDRs;
            }
        }
    }

    public void printPages() {
        System.out.println("Size: " + pages.size());
        System.out.print("Loaded: [ ");
        for (Page page : pages) {
            if (page.loaded)
                System.out.print(page.laddr + " ");
        }
        System.out.println("]");
    }

    // devuelve el ptr del proceso que debe dormir (cambia con cada ALG)
    protected abstract int whoToUnload();
    
    public void update() {
      this.updateInfo();
    }
}


private class FIFO extends Pager {
  
    FIFO(){
      super();
      this.algorythm = Algorythm.FIFO;
    }

    @Override
    protected int whoToUnload() {
        int ptr = -1;
        int maxTime = -1;
        for (Page page : pages) {
            if (page.loaded && maxTime < page.loadedtime) {
                maxTime = page.loadedtime;
                ptr = page.laddr;
            }
        }
        return ptr;
    }

}

private class SC extends Pager {

    /*@Override
    public void callUse(int ptr) {
        // Obtener paginas con el puntero
        List<Page> usePages = getPagesbyPtr(ptr);

        // Liberar espacio necesario
        int hits, misses;
        boolean loaded;
        if (!super.isLoaded(ptr)) {
            int spaceNeeded = super.sizeNeeded(usePages);
            int freeMemory = super.getFreeMemory();
            hits = Math.min(usePages.size(), freeMemory / 4000);
            misses = usePages.size() - hits;
            while (freeMemory < spaceNeeded) {
                this.unloadPages(whoToUnload());
                freeMemory = super.getFreeMemory();
            }
            loaded = false;
        } else {
            hits = usePages.size();
            misses = 0;
            for (Page page : usePages) {
                page.mark = true;
            }
            loaded = true;
        }

        // Cargar Informacion a las paginas llamadas
        loadPages(usePages, false, loaded);
        this.incrementTimes(hits, false);
        this.incrementTimes(5 * misses, true);
        updateInfo();
    }*/
    
    SC(){
      super();
      this.algorythm = Algorythm.SC;
    }
    
    @Override
    protected void loadPages(List<Page> pages, boolean isNew, boolean loaded) {
        for (Page page : pages) {
            page.loaded = true;
            page.daddr = 0;
            page.maddr = 0;
            if (isNew && !loaded) {
                this.pages.add(page);
            }
            if (!isNew && loaded) {
              page.mark = true;
            }
        }

        super.setMADDRs();

        if (isNew || !loaded) {
            this.setRamKB(pages.size() * 4);
            this.setLoadedPages(pages.size());
        }

        if (!isNew && !loaded) {
            setVirtualRamKB(pages.size() * 4 * -1);
            setUnloadedPages(pages.size() * -1);
        }
    }

    @Override
    protected int whoToUnload() {
        Integer page = getInteger();
        if (page != null) return page;
        return whoToUnloadAux();
    }

    private int whoToUnloadAux() {
        Integer page = getInteger();
        if (page != null) return page;
        return -1;
    }

    private Integer getInteger() {
        pages.sort(Comparator.comparingInt((Page p) -> p.loadedtime).reversed());

        for (Page page : pages) {
            if (page.loaded) {
                if (page.mark) {
                    page.mark = false;
                } else {
                    return page.laddr;
                }
            }
        }
        return null;
    }
}

private class MRU extends Pager {
  
    MRU(){
      super();
      this.algorythm = Algorythm.MRU;
    }
  
    @Override
    protected void incrementTimes(int seconds, boolean thrashing) {
        for  (Page p : pages) {
            if (p.loaded) {
                p.incrementTime(seconds);
                p.lastCalledTime += seconds;
            }
        }

        this.increaseTime(seconds);

        if (thrashing) {
            this.increaseThrashingTime(seconds);
        }
    }

    @Override
    protected void loadPages(List<Page> pages, boolean isNew, boolean loaded) {
        for (Page page : pages) {
            page.loaded = true;
            page.daddr = 0;
            page.maddr = 0;
            page.lastCalledTime = 0;
            if (isNew && !loaded) {
                this.pages.add(page);
            }
        }

        super.setMADDRs();

        if (isNew || !loaded) {
            this.setRamKB(pages.size() * 4);
            this.setLoadedPages(pages.size());
        }

        if (!isNew && !loaded) {
            setVirtualRamKB(pages.size() * 4 * -1);
            setUnloadedPages(pages.size() * -1);
        }
    }

    @Override
    protected int whoToUnload() {
        int ptr = -1;
        int minTime = Integer.MAX_VALUE;

        for (Page page : pages) {
            if (page.loaded && page.lastCalledTime < minTime) {
                minTime =  page.lastCalledTime;
                ptr = page.laddr;
            }
        }
        return ptr;
    }
}

private class RND extends Pager {
  
    RND(){
      super();
      this.algorythm = Algorythm.RND;
    }

    private List<Page> getLoadedPages() {
        List<Page> result = new ArrayList<>();
        for (Page page : pages) {
            if (page.loaded) {
                result.add(page);
            }
        }
        return result;
    }

    @Override
    protected int whoToUnload() {
        List<Page> loadedPages = getLoadedPages();
        int rnd = this.rand.nextInt(loadedPages.size());
        return loadedPages.get(rnd).laddr;
    }
}



static class Page {
    //static int nextID = 0;
    final int id;
    int pid;
    int laddr;
    int maddr;
    int daddr;
    int loadedtime;
    int lastCalledTime;
    boolean loaded;
    boolean mark;
    int memoryUsed;

    public Page(int id, int pid, int laddr, int memoryUsed) {
        this.id =  id;
        this.pid = pid;
        this.laddr = laddr;
        this.memoryUsed = memoryUsed;
        this.loadedtime = 0;
        this.lastCalledTime = 0;
        this.loaded = true;
    }
    
    public Page(int loadedtime, int daddr, int maddr, int laddr, int pid, int id, boolean loaded, boolean mark) {
        this.loadedtime = loadedtime;
        this.daddr = daddr;
        this.maddr = maddr;
        this.laddr = laddr;
        this.pid = pid;
        this.id = id;
        this.loaded = loaded;
        this.mark = mark;
    }

    public void setMaddr(int maddr) {
        this.maddr = maddr;
    }

    public void setDaddr(int daddr) {
        this.daddr = daddr;
    }

    public void incrementTime(int seconds) {
        this.loadedtime += seconds;
    }

    public void changeLoaded() {
        this.loaded =  !this.loaded;
    }

    public void changeMark() {
        this.mark = !this.mark;
    }
}




public void pageColor(int seed){
  randomSeed(seed);  
  float h = (seed*37+156) % 360;
  float s = 30 + (seed * 71) % 40;
  float b = 60 + (seed * 97) % 20;
  fill(h, s, b);
}

public void drawPages(List<Page> pages, int algorythm){
  // algorythm = 0/1
  int posX = algorythm * width/2 + width/12;
  int posY = 5*height/8;
  int ancho = 4*width/12;
  
  int colWidth = ancho/8;
  
  fill(0);
  posY -= 2;
  text("Page ID", posX, posY);
  text("PID", posX + colWidth, posY);
  text("Loaded", posX + colWidth*2, posY);
  text("L-Addr", posX + colWidth*3, posY);
  text("M-Addr", posX + colWidth*4, posY);
  text("D-Addr", posX + colWidth*5, posY);
  text("Loaded-T", posX + colWidth*6, posY);
  text("Mark", posX + colWidth*7, posY);
  posY += 2;
  
  for (Page page:pages){
    pageColor(page.pid); //Assigns the color of the process based on the pid
    stroke(0);
    rect(posX, posY, ancho, 15);
    
    posY += 12;
    fill(0);
    text(page.id, posX + 5, posY);
    text(page.pid, posX + colWidth + 5, posY);
    
    posX += 7;
    if (page.loaded){
      text("X", posX + colWidth*2 + 5, posY);
    }
    
    text(page.laddr, posX + colWidth*3 + 5, posY);
    if (page.maddr != 0){
      text(page.maddr, posX + colWidth*4 + 5, posY);
    }
    if (page.daddr != 0){
      text(page.daddr, posX + colWidth*5 + 5, posY);
    }
    
    text(page.loadedtime, posX + colWidth*6 + 5, posY);
    
    if (page.mark){
      text("X", posX + colWidth*7 + 5, posY);
    }
    
    posX -= 7;
    posY += 3;
  }
  
  
}

public void drawMemoryFromPages(ALG ALG){
  
  List<Page> list = ALG.pages;
  String name;
  int posY = ALG.algorythm == Algorythm.OPT ? height/8 : 3*height/16;
  int squareWidth = 10*width/12 /100; //100 RAM pages
  int posX = width/12;
  int incrementX = squareWidth;
  
  int squareHeight = 20;
  
  
  switch (ALG.algorythm) {
    case FIFO:
      name = "FIFO";
      break;
    case SC:
      name = "Second Chance";
      break;
    case MRU:
      name = "MRU";
      break;
    case RND:
      name = "Random";
      break;
    default:
      name = "OPT";
      break;
  }
  
  fill(0);
  text("[" + name + " Ram]", posX + 5, posY - 3);
  
  
  stroke(0);
  fill(360);
  
  int loaded = 0;
  for(Page page : list){
    
    if (page.loaded){
      pageColor(page.pid);
      rect(posX, posY, squareWidth, squareHeight);
      posX += incrementX;
      loaded++;
    }
  }
  
  for(int i = loaded; i < 100; i++){
    fill(360);
    rect(posX, posY, squareWidth, squareHeight);
    posX += incrementX;
  }
}


  public void settings() { fullScreen(); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "Proyecto2" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
